apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: orders-microservice
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/BHAGWAN-KBEF/microservice-devops-pipeline.git
    targetRevision: HEAD
    path: helmorders-microservice
  destination:
    server: https://kubernetes.default.svc
    namespace: orders-microservice
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true